spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/new_jiakao?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8888
logging:
  level:
    com.fc: debug
jk:
  cfg:
    corsOrigins:
      - http://localhost:63342